production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
  auto_commit_after_request: true
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8980
    log_level: INFO
  auto_commit_after_request: true

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: OFF